### ISSUE TITLE
Wrap your imperative POJOs in Functions

### ISSUE THREAD

**Issue by arnolddevos** [scalasyd/scalasyd#11]
Java APIs are usually full of factory objects, factory-factory objects and lots of  setters. You use these to build a tree of POJOs which, finally, does something for you.

If you are starting to get the hang of functional programming in scala all this imperative POJO building just does not fit in.  It is tedious and it comes up pretty often.

This short talk is about a simple way to turn it all into functions acting on values: a functional DSL.  

We will wrap the Jetty API as an example but the approach should work for many others.

I think this talk will work for new scala programmers.  The most advanced concept touched on will be be the typeclass and it will not be central.

However, in a plot twist at the very end it will be revealed that our POJO builder is, in fact, a _comonad_.  Hopefully the more learned among the crowd will then discuss comonads vigorously while I have a beer.

**Comment by arnolddevos** [comment]
After finishing this I reviewed and saw that all the uses of cobind could just as well be fmap.  In other words, this is not a genuine illustration of a comonad at work.  That takes some of the interest out of it, oh well.

**Comment by markhibberd** [comment]
@arnolddevos Can you add a note to this as to roughly when you would be able to give the talk - even if it is like - I can do this, as long as I have X weeks notice.

**Comment by arnolddevos** [comment]
At a pinch I can do this at the June 10th meetup.  Otherwise with 1-2 weeks notice.   Est. 25 min duration.

**Comment by markhibberd** [comment]
@arnolddevos Would be pretty happy for you to do June 10th. Still need one more talk. Can I lock it in?

**Comment by arnolddevos** [comment]
OK Lock it in.

**Comment by arnolddevos** [comment]
For th sake of an abstract to put on the meetup notice (which does not seem to be up yet btw) I submit this slightly modified version of original proposal text:  

Delete last 2 pars. Add:  

At the end we will see which concepts from algebra are embodied in our DSL.

**Comment by recurse** [comment]
Wondering if we could include a link to slides and/or video (if/when available) here?
