### ISSUE TITLE
A Parsing Fancy: Parser Combinators in Scala

### ISSUE THREAD

**Issue by sigerber** [scalasyd/scalasyd#12]
Introductory-level Scala talk that covers the parser combinator library. Talk is in two parts, 10-15 minutes of (really light!) theory on DSLs and context-free-grammars. With audience participation we construct a toy DSL that pits security threats against targets. A parser for this DSL is then live coded. 

The talk was previously delivered as an internal tech-talk at my company and is ready to go.

**Comment by arnolddevos** [comment]
Sounds good to me.  I see you are using the original scala library parser combinators.  Have you seen these interesting alternative parser combinators: http://lihaoyi.github.io/fastparse/ ?

**Comment by sigerber** [comment]
I hadn't seen that one before. I did learn about Parboiled2 after we finished writing our own DSL parser. However when I was putting together the talk the intention was more to drum up enthusiasm for Scala than to teach parser combinators. I felt it was better to stick with the original library since I was much more familiar with it and most of the talk is a live coding demo.

But probably I should add in a slide with some alternatives - thanks.

**Comment by arnolddevos** [comment]
I thought you might be interested in that one in particular because it is a
parser combinator library. Live coding with the original scala parser
combinators sounds good to me.

**Comment by markhibberd** [comment]
@sigerber Would you be able to do this talk in June? Meetup is June 10th..

**Comment by sigerber** [comment]
@markhibberd Yes - should be fine. Pencil it in and I'll give you a hard confirmation soon.

**Comment by sigerber** [comment]
All good to go. Btw, there are two presenters for this talk. I'm the primary presenter but my collegue Mathew Johnson will be helping out with the audience participation.

**Comment by sigerber** [comment]
@jedws Haven't been to a Scala meetup before - I assume I can bring in my own laptop for the presentation? Anything special I need to know about accessing the premises?

**Comment by jedws** [comment]
We have an HDMI projector, and MiniDVI connectors – we mostly use Macs.

As far as access goes, the lifts close at 5.30, but we have people around
to let people in until about 6.45. Turn up whenever suits you.

cheers,
jed.
