### ISSUE TITLE
Solving CSPs in Scala (with StateT and MonadPlus)

### ISSUE THREAD

**Issue by filippovitale** [scalasyd/scalasyd#14]
I would like to present a talk inspired by the [4 blog posts](http://bartoszmilewski.com/2015/05/11/using-monads-in-c-to-solve-constraints-1-the-list-monad/) by Bartosz Milewski on solving a simple constraint satisfaction problem in C++ and Haskell.

This presentation would start solving the problem in Scala using simple high-order functions and `List` for comprehension. The solution could evolve using `List.permutations` and `zip` and few quick benchmark result considerations.

I would like to then introduce `StateT[List, S, A]` and `Plus` as implemented in scalaz and refactor the solution.

**Comment by jedws** [comment]
sounds fun! when would you have it ready by?

**Comment by filippovitale** [comment]
The presentation would be ready for July

**Comment by filippovitale** [comment]
## Title and Abstract:

#### Let’s mash 2 monads to solve a simple CSP

Intermediate–level Scala talk that cover the 4 blog posts by Bartosz Milewski on solving a simple constraint satisfaction problem in C++ and Haskell.

Starting from an imperative–style implementation we will get to a pure FP–style solution surprisingly similar to the Haskell one promoted by Bartosz.

http://bartoszmilewski.com/2015/05/11/using-monads-in-c-to-solve-constraints-1-the-list-monad/

Filippo Vitale
