### ISSUE TITLE
i18n à la gettext

### ISSUE THREAD

**Issue by ngocdaothanh** [scalasyd/scalasyd#15]
.properties file (or its variants) is a popular way to add i18n to programs. But .properties file is not very easy to manage. This lightning talk introduces an alternative, easier workflow, in the [GNU gettext](http://en.wikipedia.org/wiki/Gettext) style.

Demos:
- How to write i18n messages.
- How to automatically extract the messages to a resource file be translated.
- How to automatically update existing resource file, e.g. adding or modifying messages.
- How to load and merge multiple resource files in a program.

Tools used:
- [scala-xgettext](https://github.com/xitrum-framework/scala-xgettext) (Scala compiler plugin)
- [scaposer](https://github.com/xitrum-framework/scaposer) (parser combinator)
- [poedit](http://poedit.net/) (visual GUI editor)

Related tool: [play-xgettext](https://github.com/georgeOsdDev/play-xgettext)

**Comment by markhibberd** [comment]
@ngocdaothanh When do you think you could have this talk ready by - just so I know for scheduling etc...

**Comment by arnolddevos** [comment]
I like the idea of having some short talks.

**Comment by markhibberd** [comment]
@ngocdaothanh More concretely, do you think you would have this ready for the June meetup (June the 10th).

**Comment by ngocdaothanh** [comment]
Hi. I think I'll be ready by that time.

**Comment by markhibberd** [comment]
@ngocdaothanh Can you send me a mail to mark@hibberd.id.au.

**Comment by ngocdaothanh** [comment]
@markhibberd I've sent you a mail.
