### ISSUE TITLE
Scala’s Modular Roots

### ISSUE THREAD

**Issue by tmcgilchrist** [scalasyd/scalasyd#16]
Investigate the inspiration Scala has taken from Modula-2, Modula-3, Haskell, and Standard ML. 
In particular look at the equivalence between Scala and Standard ML's module system.

```
Object ≅ Structure
Class ≅ Functor
Trait ≅ Signature
Abstract Type ≅ Abstract Type
Refinement ≅ Sharing Constraint
```

**Comment by markhibberd** [comment]
When do you think you would be able to prepare such a talk?

**Comment by tmcgilchrist** [comment]
Nothing concrete written yet, could be ready for the July meetup on the 15th.

**Comment by jedws** [comment]
@tmcgilchrist can you please provide a title and one sentence description please?

also note this is on July 8th (second Wednesday of the month).

**Comment by tmcgilchrist** [comment]
Still working on the talk, so something like this is probably appropriate for now.

### Scala's Modular Roots

How Scala drew inspiration from Standard ML’s module system aka how to write some ML in your Scala.
