### ISSUE TITLE
Entry level talk on Functor, Apply, Applicative, Bind and Monad.

### ISSUE THREAD

**Issue by oliverdaff** [scalasyd/scalasyd#19]
Entry level talk on Functor, Apply, Applicative, Bind and Monad.  
1. Provide an overview of each of their implementations in Scalaz 
2. Give real world examples about when and how you would consider using each of them.

This talk will be ready for the July meetup.

**Comment by filippovitale** [comment]
:+1:

**Comment by jedws** [comment]
@oliverdaff I know this is late notice, but would you be ready for next week?

**Comment by oliverdaff** [comment]
Sorry @jedws I can't make the meetup this month, I can do September though.

**Comment by jedws** [comment]
@oliverdaff k, so next week then?

**Comment by oliverdaff** [comment]
@jedws yes next Wednesday is fine, how long do you want the talk to be?

**Comment by jedws** [comment]
30-40 mins, do you have any further description you want for it?

**Comment by oliverdaff** [comment]
Hi @jedws 

Functor, Apply, Applicative and Monad looking at how they work, why you should use them in your software and examples implemented in Scalaz.

**Comment by ngocdaothanh** [comment]
@oliverdaff Can you kindly add a comment containing the link your presentation file to [the meetup page](http://www.meetup.com/scalasyd/events/225084242/)? Your talk was great, I want to I want to read your presentation file to study Scalaz but can't find it anywhere.

**Comment by oliverdaff** [comment]
Hi @ngocdaothanh I'm glad you enjoyed the talk, apologies for being slow getting the slides out. I'll get the slides into a pdf and posted over the weekend.

**Comment by oliverdaff** [comment]
Hi @ngocdaothanh I've posted the slides on slideshare http://www.slideshare.net/oliverdaff/functor-apply-applicative-and-monad as promised.

**Comment by ngocdaothanh** [comment]
:+1:
