### ISSUE TITLE
Life without stacktraces

### ISSUE THREAD

**Issue by charleso** [scalasyd/scalasyd#20]
Would probably be fairly short (intro-level) talk. 
EDIT: Actually it's starting to turn in to a full 30-minute talk.
1. Why we (used to) like stacktraces
2. Why/when we start to lose stacktraces with trampolining 
3. How to do safe error handling (or at least one way) - the meat of the talk
4. Why this is better than stacktraces anyway

Or something like that.

``` scala
sealed trait UserError

def loadUser(...): EitherT[IO, UserError, User]

sealed trait ServiceError
case class UserServiceError(e: UserError) extends ServiceError
case class FooServiceError(e: FooError) extends ServiceError

def loadFoo(...): EitherT[IO, ServiceError, Foo] =
  for {
    u <- loadUser().leftMap(UserError(_))
    f <- loadFoo(u).leftMap(FooError(_))
  } yield f

// and so on...
```

Would people find this interesting/useful?

**Comment by jedws** [comment]
+1

**Comment by newhoggy** [comment]
+1

**Comment by filippovitale** [comment]
:+1:

**Comment by etorreborre** [comment]
:+1:

**Comment by jedws** [comment]
@charleso you up for October?

**Comment by charleso** [comment]
@jedws Not really. :( I've been working on a Haskell workshop for November and haven't had time to look at this. It would be very unprepared, which I think would make for a bad talk.

**Comment by jedws** [comment]
bugger, we unfortunately have an empty cabinet next month

**Comment by charleso** [comment]
While not finished yet the slides are in a semi-reasonable state now.

http://blog.charleso.org/life-without-stack-traces/

**Comment by jedws** [comment]
k,good stuff!.

unfortunately, I'm going to cancel the ScalaSyd for this month, we have no other talks and I shall probably be away anyway.

**Comment by charleso** [comment]
Bugger.

**Comment by arnolddevos** [comment]
I did not realise there was a shortage of talks. Maybe 3 talks per night is too many.  I think audience and presenter can be pretty tired by talk 3.
