### ISSUE TITLE
Eric Torreborre: talk about ambiata/origami

### ISSUE THREAD

**Issue by etorreborre** [scalasyd/scalasyd#21]
This talk presents Origami, a [library](http://github.com/ambiata/origami) providing "monadic folds" to accumulate values (like mean, standard deviation, min/max) on "streams" of values which can be coming from iterators, scalaz-stream processes or Akka data flows.

**Comment by markhibberd** [comment]
@jedws Confirmed with @etorreborre that this is good for next week.

**Comment by jedws** [comment]
@etorreborre can you provide a final description and title?

**Comment by etorreborre** [comment]
@jedws let's keep the original description:

```
title: Origami, monadic folds for Scala

abstract: this talk presents Origami, a library providing "monadic folds" to accumulate values 
(like mean, standard deviation, min/max) on "streams" of values which can be coming from 
iterators, scalaz-stream processes or Akka data flows.
```

**Comment by jedws** [comment]
cool, thx!
