### ISSUE TITLE
Interpretation of Pattern matching in Scala

### ISSUE THREAD

**Issue by altmattr** [scalasyd/scalasyd#23]
I can talk about "compiled vs interpreted pattern matching" in the scala/haskell context. The main point is that scala is doing lots of "interpretation" when picking which case statement to execute. There are huge benefits to this, which I will talk about, but also performance penalties. I will include an account of Extractor Objects if you think a significant number of people will need that. A Haskell-focussed version is available at https://wiki.mq.edu.au/display/plrg/Compiled+and+Interpreted+Pattern+Matching but I will do a more scala-ish talk for scala-syd. NB: I can now see the images are broken in that article :/

**Comment by etorreborre** [comment]
:+1: I would be interested in what's knowing more about both translation schemes.

**Comment by jedws** [comment]
@altmattr would you be ok to do this for the October 14 meetup?

**Comment by altmattr** [comment]
sure can.

Matt

**Comment by jedws** [comment]
excellent, consider yourself booked!

**Comment by jedws** [comment]
@altmattr Matt, can you send me or post here a short title and description and your full name? email jed at wesleysmith dot io, cheers!

**Comment by jedws** [comment]
Matt, sorry, worked out from the link your full name, ignore me. Will extract a description but send through if edits required.
