### ISSUE TITLE
fun with scalaz-streams

### ISSUE THREAD

**Issue by da-terry** [scalasyd/scalasyd#24]
I can do a talk on various little things I'm regularly doing with/to streams, like:
- async (merge / queue / topic)
- fluent DSL with implicit classes
- transducers, reduce etc.

**Comment by etorreborre** [comment]
:+1: I am very interested in this, I hope you can do it for the December meetup.

**Comment by da-terry** [comment]
I should be able to get a talk together for December

**Comment by jedws** [comment]
I'm afraid it looks like our next meetup won't be until February.

**Comment by da-terry** [comment]
Aw really? Bummer. Well, I can do February as well :p

**Comment by jedws** [comment]
do you think you can do March?

**Comment by jedws** [comment]
scheduled for March 9 http://www.meetup.com/scalasyd/events/229271693/
