### ISSUE TITLE
Shapeless hacking - exploring the power of the Dark Side

### ISSUE THREAD

**Issue by triggerNZ** [scalasyd/scalasyd#25]
# An intro to dark-side typelevel programming with shapeless
- A demo of some cool things that are possible
- Type-level programming techniques in Scala, focusing on shapeless
- Some warnings about how overdoing this stuff can be dangerous
- Encouragement to ignore the dangers and embrace the raw power
- Star Wars references.

I'm happy to do this in March, or any time a slot is available.

**Comment by jedws** [comment]
excellent, sounds great! consider your self booked for March.

**Comment by jedws** [comment]
scheduled for March 9 http://www.meetup.com/scalasyd/events/229271693/
