### ISSUE TITLE
Type Member vs Type Parameter: Which? Why?

### ISSUE THREAD

**Issue by arnolddevos** [scalasyd/scalasyd#26]
Path dependent types distinguish scala from other commonly used languages. But what can we do with PDT's that we can't (easily) do by introducing type parameters?  In other words, why do we care about PDTs?  

In a recent paper about DOT Odersky et al show an example of the usefulness of PDTs.  But this example is easily recoded with type parameters. See here: https://gist.github.com/arnolddevos/09e5f51ce1436f590c7d 

This talk will give a few more examples and we will see if any of them are convincing.  May the superior idiom survive!

At the end, if it is not too much, the encoding of type parameters in PDTs will be shown.

**Comment by etorreborre** [comment]
Hi Arnold, pedantic question but shouldn't the talk be named "Type members vs Type parameters"? Path-dependent types are a consequence of having type members.

**Comment by arnolddevos** [comment]
Well scala is not the only "commonly used" language with type members.  Associated types in Rust seem to fit that description. The path dependence is what makes scala's type members different. It makes the given example work in scala while it would not work in Rust.  More deeply, path dependence is what makes DOT tick and enables encoding of several, formerly different, type system concepts in terms of this one concept.

**Comment by arnolddevos** [comment]
Hi again Eric, I am still thinking about your comment above.  Maybe my proposed talk should be advertised as "Type Member vs Type Parameter .."  and it can "emerge" in the talk that type members are path dependent and what that means and why it is significant.

**Comment by jedws** [comment]
sounds good to me

**Comment by etorreborre** [comment]
@arnolddevos I agree, path-dependent types is a much stronger property of the type system. Otherwise type members are just "named" type parameters, with rules for overriding etc... that you have for members in general.

**Comment by arnolddevos** [comment]
@jedws do you want this talk next week?  if so, I had better prepare.

**Comment by jedws** [comment]
@arnolddevos yes, I certainly hope so – I announced it already! 

http://www.meetup.com/scalasyd/events/229271693/

**Comment by arnolddevos** [comment]
All good.  This talk will aim to be meaningful to all (not just scalazi and other bearded ones) and will run strictly to time.  No need to relegate me to the midnight (I mean #3) slot. :-)

**Comment by jedws** [comment]
no worries, will try and work out a good running order

**Comment by jedws** [comment]
scheduled for March 9 http://www.meetup.com/scalasyd/events/229271693/
