### ISSUE TITLE
Order this Wednesday

### ISSUE THREAD

**Issue by triggerNZ** [scalasyd/scalasyd#27]
I noticed that both myself and @arnolddevos are speaking about type-level programming this week. It may be worth coordinating to find the optimal order. It seems to me that 'Type Member vs Type Parameter: Which? Why?' should come first, but @arnolddevos, I would value your opinion. I can add you to my private slides repo if it helps.

**Comment by arnolddevos** [comment]
Also, one of my examples is a simple HMap (different to the shapeless one).  I am trying to keep my talk at a simple level but it is a battle.     It would be great if I could include some forward references to your talk.

**Comment by triggerNZ** [comment]
That's cool. I don't present HMaps so we should be fine :). Actually I don't present much of the shapeless API, I am more trying to demonstrate recursive-style type level programming, because that is what shapeless is pretty much always doing under the hood.

Added you to to my talk repo, content is at `slides/slides.md`. I will make some further changes, but it is 90% complete

**Comment by arnolddevos** [comment]
I am not doing any examples with recursive types, eg HList.  More like the opposite, heterogeneous collections where the types are lost to the world outside.

**Comment by triggerNZ** [comment]
Cool! Nice review of related but nonoverlapping concepts then :+1:

**Comment by arnolddevos** [comment]
Yes, good.  When @jedws  catches up with this thread: I can go in any position on the card notwithstanding my preference to avoid the graveyard shift.

**Comment by triggerNZ** [comment]
Since it looks like we don't have dependencies, I am fine with any order

**Comment by jedws** [comment]
seems like Arnold then Tin would be a good fit. Dunno where that will leave
Alex, perhaps first.

**Comment by da-terry** [comment]
I'm cool with any slot.
