### ISSUE TITLE
Immutable Infrastructure using FP design patterns

### ISSUE THREAD

**Issue by charleso** [scalasyd/scalasyd#29]
@nhibberd

**Comment by charleso** [comment]
@nhibberd Would you be OK to do this talk on April 13th? If so do you mind adding an abstract?

**Comment by charleso** [comment]
@jedws Doesn't look like Nick is going to have time to finish this before next week. Want me to talk to Chris to see if he can do the LightBend talk after all?

**Comment by jedws** [comment]
I'll leave it in your capable hands @charleso !
