### ISSUE TITLE
What the hell is lightbend?

### ISSUE THREAD

**Issue by charleso** [scalasyd/scalasyd#30]
Hey @jedws, did you manage to get a confirmation from James/Chris about doing a talk this month?

**Comment by jedws** [comment]
@charleso no, sorry, haven't heard anything from them

**Comment by huntc** [comment]
I'm happy to come and chat about what Lightbend is.

I presume that you would like to understand its relationship with Scala, and also the Scala Centre?

Perhaps you could elaborate further on what you'd like to understand.

**Comment by jroper** [comment]
I'm a bit busy this month, but if you want an answer to your question, there's actually three answers:

https://en.wikipedia.org/wiki/Refraction
https://en.wikipedia.org/wiki/Diffraction
https://en.wikipedia.org/wiki/General_relativity

**Comment by charleso** [comment]
@huntc @jroper Actually we managed to find another talk. Might be good to catch up at ScalaSyd to talk about what we're looking for (the short answer being that it's pretty open ended).

**Comment by jroper** [comment]
I actually live in Canberra now, so I don't make it to ScalaSyd that often.

**Comment by huntc** [comment]
I'll come up for the next one and we can chat then. Cheers.

**Comment by huntc** [comment]
As per chat with @charleso - I'm happy to do a chat on Lightbend, Scalacenter etc. Keep the title as per this issue - I like it!
