### ISSUE TITLE
Macro-based smart constructors

### ISSUE THREAD

**Issue by mjhopkins** [scalasyd/scalasyd#31]
Smart constructors are a nice pattern for building data types that need extra validation or calculation.

But in the case when we're building our data type from statically known values, they leave us with two annoyances:
- it's more clunky
- we have a run-time test for something that's known at compile time.

We'll investigate how Scala macros can help us address these problems while retaining safety.

**Comment by charleso** [comment]
Thanks @mjhopkins, very much appreciated.
