### ISSUE TITLE
scala.js

### ISSUE THREAD

**Issue by charleso** [scalasyd/scalasyd#32]
https://www.scala-js.org/

Would be even better if we could find someone using it in production.

**Comment by charleso** [comment]
Kindly suggested by @arnolddevos

**Comment by charleso** [comment]
I believe @japgolly might be able to help us out here (no pressure though). :)

**Comment by japgolly** [comment]
Yes! and no.

I'm not really interested in doing an Introduction to Scala.JS in isolation. It's a bit low-level, introductory and the ratios of topic passion, time to craft talk, and available time don't work. It's not quite the same but there are also a heap of fantastic talks and demos online by Li Haoyi that show off and explain Scala.JS itself.

I *would* be interested in doing a talk on purely functional webapps in scala (with scalajs-react). Scala.JS would be a critical part of that but I would be using it as the lower level building block on which I build higher level stuff which I find more exciting to talk about right now. I've got a bunch of stuff floating around in my head in this space that would make a good talk.... If I stop trying to cram so much in to one, I've probably got 3 talks. They'd all just skim over Scala.JS though.

**Comment by japgolly** [comment]
> They'd all just skim over Scala.JS though.

As in I'd squash an introduction to what it is, how it works and how to use it, into <5 min.

**Comment by charleso** [comment]
> I would be interested in doing a talk on purely functional webapps in scala

Sounds perfect to me. I'm definitely a fan of more applied talks than just dry introductions. If that introduces people to the concept of Scala.js along the way then that sounds like a win.

If/when you feel prepared to give a talk on that don't hesitate to hijack this issue and rename/update, or alternatively create a new one.

**Comment by japgolly** [comment]
Yeah, will do! Let me keep ruminating on it and I'll get back to you. If anyone wants to do more introductory talk though please go for it.

**Comment by karlroberts** [comment]
Hi I'm currently writing a Markdown Parser in Scala.js happy to prep a talk sometime. Although I haven't used it in anger yet it is promising, also highlighted some of the strange issues and compiler warnings that can hit you when using scala.js. Kind of bridge the gap from the Hibberd's "dont fear the parser" and implementaton in Scala.js

**Comment by charleso** [comment]
@karlroberts That sound pretty good. I think @japgolly is keen to do something on scala.js + react. I'll take what I can get though. :) We should chat next meetup and see what people are most passionate about.

**Comment by karlroberts** [comment]
@charleso OK although I wont be able to go tonight! happy to have different use cases: japgolly can do  the full SPWA using scala.js -> react components. I can do my js markdown lib created with scala.js using combinator parsers. I hope to get time to try and package it properly into npm too so that to the js world it is transparent. Just doing this has highlighted a few gotchas of using/developing with scala.js which will be interesting info nuggets for people who want to try it. Should be able to have something ready for 2months from now Sept 2017 or at a push  Aug 2017. Let me know

**Comment by charleso** [comment]
@karlroberts Thanks. I wonder whether it would be "fun" to have a themed night, and have both talks about scala.js? I'll talk to @japgolly if he's there tonight.

**Comment by karlroberts** [comment]
@charleso Haha yeah and cross post it to the js meetups! :-)

**Comment by charleso** [comment]
@japgolly You interested in doing a talk on scala.js next month? If so I'm tempted to line up you and Karl for a double scala.js wammy. I'm open to suggestions though.

**Comment by arnolddevos** [comment]
@charleso this would be great.  If it will be a scalajs night I will postpone my talk.

**Comment by japgolly** [comment]
Hey. Unfortunately I've had too much on to even attend ScalaSyd lately let alone prepare a preso. Next month will be the same but, we could lock in a talk for Sep? Either Oct or Nov would be ok too but I'll need to check something before I can reliably say which.

I could talk for weeks about Scala.JS + FP + React. I'm thinking a whirlwind tour would be a good first talk. Cover a bunch of things without getting too deep into any one point. It def won't cover publication to npm or Scala→JS interop so @karlroberts and I will have lots of different ground to cover.

**Comment by japgolly** [comment]
Oh I :+1: on the idea of a Scala.JS themed night!

**Comment by charleso** [comment]
@japgolly Let's tentatively lock in Sep then if that works for you.  A whirlwind tour would be good if we're doing a themed night, but I'm happy to let you and @karlroberts work out who does what. @karlroberts You OK with Sep too?

**Comment by japgolly** [comment]
*This just in:*
It turns out I can't do Oct or Nov, ...or Dec, or n+1. September's all I can do, I'm afraid.

**Comment by charleso** [comment]
@japgolly September is perfect. I'm looking forward to seeing the talks. :)

**Comment by karlroberts** [comment]
ok Im in for Sept. :-)

**Comment by japgolly** [comment]
I guess you'll be announcing on meetup.com soon, how about this for the title of mine: *"Purely Functional Webapps with scalajs-react"*

What's the date?

**Comment by charleso** [comment]
@japgolly For historical reasons I only usually announce a week in advance. It's always the second Wednesday of the month, so it's the 13th of September.

Thanks for the title. Got a description while you're here?

**Comment by japgolly** [comment]
Ok thanks, I'll keep the 13th in mind.

For a description, let go with this:

> scalajs-react is a Scala library that allows you to write webapps that remain easy and safe to dev/extend/maintain/reason-about as your project scales from toy→real app→behemoth. This talk includes introductions to FP and Facebook's JS library, "React"; an in-depth tutorial to the basics of scalajs-react and some key features; followed by a quick whirlwind tour of other available resources for building a serious, high-quality webapp. Only prerequisite: knowledge of Scala itself.

**Comment by charleso** [comment]
@karlroberts You got a title/description in mind for your talk?

**Comment by charleso** [comment]
@karlroberts Ping again, you have a good title/description?

**Comment by charleso** [comment]
@japgolly and @karlroberts thanks heaps for the great talks!
