### ISSUE TITLE
The Expression Problem, Trivially

### ISSUE THREAD

**Issue by inkytonik** [scalasyd/scalasyd#33]
A nice talk might be constructed around this four-page paper: [The Expression Problem, Trivially](http://i.cs.hku.hk/~bruno/papers/Modularity2016.pdf) by Wang and Oliveira. The paper describes what the expression problem is and gives a new very simple solution in Scala. This result is surprising since many people have tried  for many years to solve the expression problem in sometimes quite complex ways.

This talk might suit a speaker with limited time to prepare a talk since there's not too much to it and it can be based closely on the content of the paper. The Scala that is involved is not complex, so it might also suit a speaker who is not very experienced with the language.

**Comment by altmattr** [comment]
I would be interested in presenting this paper - I can do it this month if necessary.

**Comment by charleso** [comment]
@altmattr That would be great. We might actually have enough speakers! Can I lock this in?

**Comment by altmattr** [comment]
@charleso lock it in

**Comment by charleso** [comment]
@altmattr Brilliant!

**Comment by charleso** [comment]
Thanks @altmattr !
