### ISSUE TITLE
Scala 2.12, Java 8 and You

### ISSUE THREAD

**Issue by charleso** [scalasyd/scalasyd#34]
Might be good to have a talk about the upcoming Scala 2.12, and in particular the interaction with Java 8.

**Comment by jhinch** [comment]
Are you still looking for a speaker to talk on this topic?

**Comment by charleso** [comment]
@jhinch Not as of yet. It's all yours if you want it!

Is it something you would be looking to give next month, or would you want more time to prepare? (No rush, just asking)

**Comment by jhinch** [comment]
I'd be happy to give the talk. If you need a talk for next month I think I can manage to put it together.

**Comment by jedws** [comment]
@jhinch consider yourself booked!

**Comment by charleso** [comment]
@jhinch You good for next month - the 6th of July?

**Comment by jhinch** [comment]
Yep. All good. Sorry, I would have confirmed last night but I was unable to attend the June meetup

**Comment by charleso** [comment]
Sweet! Thanks. :)

**Comment by charleso** [comment]
@jhinch Did you have a title/description for your talk that you want use to use for the meetup event?

**Comment by jhinch** [comment]
@charleso how about:

**Title**: Scala 2.12: A byte size code exploration

**Description**: Jason Hinch will take you on a low level tour of the upcoming Scala 2.12 release, looking into how well it makes use of the Java 8 platform and how it affects you.

**Comment by charleso** [comment]
@jhinch Sounds good!

**Comment by charleso** [comment]
Thanks @jhinch
