### ISSUE TITLE
Higher-Kinded Types

### ISSUE THREAD

**Issue by charleso** [scalasyd/scalasyd#39]
Previous time we saw this was [Episode 33](http://www.meetup.com/scalasyd/events/220240445/) and [Episode 24](http://www.meetup.com/scalasyd/events/173470592/) before that.

Keeping it at the intro level might be good.

**Comment by jedws** [comment]
I'm up for this

**Comment by charleso** [comment]
Cool. Want to do this in August?

**Comment by jedws** [comment]
sure

**Comment by charleso** [comment]
@jedws Did you have a title/description that I can use for the meetup page?

**Comment by jedws** [comment]
### Types of a Higher Kind

Scala's type system is a significant advance on Java's. One of the most important features is Higher Kinded Types, as it allows abstracting across containers and type constructors. What does this mean and how does it lead to powerful, generic libraries like scalaz and others? This talk will introduce these concepts and explain how to use them effectively.

**Comment by charleso** [comment]
Thanks Jed!

**Comment by charleso** [comment]
Thanks @jedws !
