### ISSUE TITLE
Algebraic Data Types

### ISSUE THREAD

**Issue by charleso** [scalasyd/scalasyd#41]
Talk about folds too

**Comment by jinilover** [comment]
Just a type, why called Algebraic Data Type?
Algebraic Data Type is an essential feature in functional programming.  The idea is quite simple and we are using it every day without aware of its algebraic nature.  This introductory talk will explain how algebraic this data type is, why it is important in FP.  It will also introduce how Scala, a JVM, object-oriented, language implements this feature.

**Comment by tmcgilchrist** [comment]
When's this one scheduled for @charleso I'll touch on a few ADT things in my talk this month, but if I know there is another more detailed talk I'll skip over things.

**Comment by charleso** [comment]
@tmcgilchrist It's scheduled for next month too.

Whoops, I didn't even think of the overlap. Not sure if that's a good thing or not. It's a "theme" now I guess.

**Comment by charleso** [comment]
Thanks @jinilover! I hope it went well and I'm sorry I wasn't there to see it.
