### ISSUE TITLE
Library tour: FastParse

### ISSUE THREAD

**Issue by arnolddevos** [scalasyd/scalasyd#42]
I recently used fastparse and thought it was pretty nice.

http://www.lihaoyi.com/fastparse/

> FastParse is a parser-combinator library for Scala that lets you quickly and easily write recursive descent parsers in Scala.

**Comment by charleso** [comment]
@arnolddevos You mind if I change this issue to being a specific proposal from you about fastparse?

**Comment by arnolddevos** [comment]
@charleso I guess I have a general suggestion and (I concede) a specific proposal.   So, OK, change it.

**Comment by charleso** [comment]
@arnolddevos Yeah not sure what to do with general suggestions - almost feels like a section on the `README.md` for general talk ideas.

**Comment by charleso** [comment]
@arnolddevos Thinking about it some more this might be a good talk for next month, you interested?

**Comment by arnolddevos** [comment]
@charleso At your service:   I will go ahead and prepare something.  This would continue the theme of @markhibberd 's parser talk and will be at the 'easy-ish' level.  

We will develop a parser for the 'ledger' accounting journal format defined here http://ledger-cli.org/3.0/doc/ledger3.html#Journal-File-Format-for-Developers 

In case you have never heard of it, various software has been written, over the years, to process ledger files.   Here: http://plaintextaccounting.org/#ledger-likes   you can see examples in various languages including scala and haskell.  The scala software uses the old parser combinators.

**Comment by charleso** [comment]
@arnolddevos Did you have a title/description for your talk that you want use to use for the meetup event?

**Comment by arnolddevos** [comment]
@charleso "exploring scala libraries: fastparse" Continuing the recent theme of parsing, this talk shows off a full featured, fast and easy to use parser library.  Those coming to scala from java or python will see a very different approach to creating robust parsers.  We will touch on parsers, internal DSL's, external DSL's and double entry bookkeeping.

**Comment by arnolddevos** [comment]
@charleso I assume the scalasyd meeting will be on 13th July?

**Comment by charleso** [comment]
@arnolddevos Thanks! The 13th is my current assumption.

**Comment by arnolddevos** [comment]
@charleso feel free to edit that title/description

**Comment by charleso** [comment]
Thanks @arnolddevos
