### ISSUE TITLE
Karl Roberts: How I invented Lenses

### ISSUE THREAD

**Issue by jedws** [scalasyd/scalasyd#5]

**Comment by karlroberts** [comment]
By seeing a pattern, re-factoring to extract as a function I eventually invented Lenses :-)
low level talk (i think) simply shows how all roads lead to scalaz, but also shows a lens use case and the motivation. I often think that with the higher level abstractions the motivation is no longer obvious to beginners. This talk is an anecdote showing how a need and motivation and a disire to keep refactoring took me towards Lenses.

**Comment by karlroberts** [comment]
Hi Jed / Mark

Am I doing this this month?
Cheers

Karl

**Comment by jedws** [comment]
yep, if you're up for it!

**Comment by karlroberts** [comment]
yep Wed 14th Oct right? 2nd Wed in the month?

**Comment by jedws** [comment]
yep, next week
