### ISSUE TITLE
Comparing reader writer patterns

### ISSUE THREAD

**Issue by stephennancekivell** [scalasyd/scalasyd#51]
Hi, Im interested in giving a presentation comparing reader and writer patterns. But I think this has been touched on a few times before.

Do you think this would be a good topic ?

I want to emphasise to newbies how use of the type system can help prevent errors.

Comparing
- type casting
- inheritance
- implicit converters

**Comment by charleso** [comment]
@stephennancekivell Thanks for the offer, I don't think the fact that we've seen it before is necessarily an issue. That said, would you be ok with catching at next ScalaSyd to discuss your talk and walk through what you had in mind?

**Comment by stephennancekivell** [comment]
Sure sounds good.

**Comment by stephennancekivell** [comment]
Hey @charleso,

Heres my repo with some simple comparisons.
https://github.com/stephennancekivell/type-converter-patterns/tree/master/src/main/scala

As discussed my plan is to lead people through casting and inheritance to type classes. While pointing out how to write safer code. Runtime vs compile time errors, and simple error message composition.

At the end There will be a shout out to popular libraries that do this well like argonaut, play-json, anorm, circe.io, slick.

The talk could be called, "3 way to write a json parser. A tour of scala language features". And obviously the techniques are applicable in all sorts of use cases. 

You'll see in my example code, I have both the reader and writer side of the conversions. However I dont think its required to actually showing all of it. I can get the point across with just one side.

Cheers,
