### ISSUE TITLE
Building trust free apps in a hostile world

### ISSUE THREAD

**Issue by MichaelShaw** [scalasyd/scalasyd#52]
Synchronization of data across multiple systems can be painful, especially for systems that can't guarantee a reasonable level of uptime.

From first principles we'll design a multi-master eventually consistent data store using CRDTs (Commutative Replicated Data Types) to serve as the backbone of distributed apps that can work without a constant connection to central servers.

We'll look at the intersection of CRDT theory and user experience and attempt to address some of the real world issues that come up when using them for a general purpose workload, including performance, compaction, data modelling, orderings and merge functions.

This approach has it's limitations but brings with it some strong upsides with respect to privacy, latency, uptime and sleeping easier through going "serverless" (read: using someone else's).

**Comment by charleso** [comment]
@MichaelShaw Did you have a slight more fleshed-out description that I can use for the meetup page?

**Comment by MichaelShaw** [comment]
Sure, will write something up later today.

**Comment by charleso** [comment]
Thanks @MichaelShaw !
