### ISSUE TITLE
Semi-Indexing JSON

### ISSUE THREAD

**Issue by newhoggy** [scalasyd/scalasyd#56]
An in memory JSON DOM can occupy around an order of magnitude more space in memory than the equivalent text representation of the same JSON.  This talk proposes to build a small semi-index over JSON text that allows DOM-like navigation of the JSON text without actually parsing it.

**Comment by karlroberts** [comment]
+1

**Comment by charleso** [comment]
Thanks @newhoggy! I hope it went well and I'm sorry I wasn't there to see it.
