### ISSUE TITLE
Testing for dummies

### ISSUE THREAD

**Issue by triggerNZ** [scalasyd/scalasyd#57]
In the spirit of doing more beginning talks:
## Scala testing for dummies
- A quick overview of the various libraries out there
- Unit tests
- Integration tests with mocks/fakes where required
- Property-based testing
- Starting with a simple "service" function, live-coding and running some tests for it at each of the three levels.

Aimed at beginners, experienced Scala developers who are shipping code already probably won't get too much out of it.

Can present whenever

**Comment by charleso** [comment]
@triggerNZ Excellent! We might have a beginner talk scheduled for September already, but can I put you down for October 12th?

**Comment by triggerNZ** [comment]
Sure :+1:

**Comment by charleso** [comment]
@triggerNZ Just want to confirm, are you OK to talk next Wednesday?

**Comment by triggerNZ** [comment]
@charleso actually something personal came up and i won't be able to do next week. So sorry! Any chance of bumping it?

**Comment by charleso** [comment]
@triggerNZ No worries. I hope everything is OK. Sounds like you would be up for next month though?

**Comment by triggerNZ** [comment]
Yep next month will be fine :+1:

**Comment by charleso** [comment]
@triggerNZ Time flies! You ready for next week?

**Comment by triggerNZ** [comment]
@charleso yep :+1:

**Comment by charleso** [comment]
Thanks @triggerNZ, great talk. I think I've decided we should have another property-testing talk very soon, it's been almost 2 years since the last one!
