### ISSUE TITLE
Scala @ Macquarie

### ISSUE THREAD

**Issue by jousby** [scalasyd/scalasyd#58]
- How we used Gradle as a polyglot build tool to help get Scala in the door amongst existing Java teams. 
- A polyglot grade build case study (NodeJs/React + Scala REST API + Flyway Schema Evolutions).

**Comment by charleso** [comment]
@jousby Time flies! You ready for next week?

**Comment by jousby** [comment]
@charleso thanks for the reminder. Yep all good for next week.

**Comment by charleso** [comment]
Thanks @jousby, great talk. I'm interested in hearing about the Scala DSL at some point. ;-)
