### ISSUE TITLE
Scala Tricks with Futures

### ISSUE THREAD

**Issue by stephennancekivell** [scalasyd/scalasyd#60]
Scala Tricks with Futures
-------------------------
* Talk about Futures (scala.concurrent.Future), why you might want to model time and threads or async
* Basic usage, map / flatMap. These are not promises, we don't fulfil them they are composed.
* Describe how you do many things concurrently and put them together. Sequence. Show how to write Sequence. 
* Describe why you might want to do async things sequentially, to limit load and introduce Traverse. Show how easy it is to write Traverse.
* Show how you can easily combine traverse and sequence to build a crude parallelism factor.
* Monads! Explain that this was done using monad composition, and that monads are not scary hard stuff for only mathematicians. The aim here is to wet the appetite without providing a full formal definition.

I gave this talk at work and it was well received.

**Comment by charleso** [comment]
@stephennancekivell Just out of curiosity, how long roughly is your talk likely to be? You ok with speaking on Dec 14th?

**Comment by stephennancekivell** [comment]
Hi, yea I could do then. It's probably 30-40 minutes. I can adjust the time
on the fly pretty easy. I'll also ask how long I need to spend on the
basics, hopefully not too long.

**Comment by charleso** [comment]
@stephennancekivell Awesome. My personal suggestion is to cap the talk to 25-30 minutes max and cut scope accordingly. :) The audience is (always) going to be mixed, so you really just have to decide what you most want to cover.

If you get a second, did you mind posting a fluffy description of the talk that I can use for the next Meetup? I'm not going to announce it until month so no rush.

See you next ScalaSyd. :)

**Comment by stephennancekivell** [comment]
Sure thing. Thanks

**Comment by stephennancekivell** [comment]
Hi @charleso. Heres what I've got for a talk description, Thanks.

Tricks With Futures
--------------------
Stephen Nancekivell

How you can use scala Futures for Asynchronous programming and some easy tricks for working with them.

**Comment by charleso** [comment]
Thanks @stephennancekivell. The next ScalaSyd will be on the 14th, you still OK to speak then?

**Comment by stephennancekivell** [comment]
Yea mate. Looking forward to it.

**Comment by charleso** [comment]
Scheduled!

https://www.meetup.com/scalasyd/events/236084883/

**Comment by etorreborre** [comment]
@charleso would that be possible to paste a link to the presentation slides on github once a talk has been given?

**Comment by charleso** [comment]
@stephennancekivell did you mind posting the slides either here and/or to the meetup page after the event?

**Comment by stephennancekivell** [comment]
Yea sure, no worries guys.

**Comment by stephennancekivell** [comment]
Hey @etorreborre the slides are in this repo.
https://github.com/stephennancekivell/fun-futures

**Comment by etorreborre** [comment]
@stephennancekivell thank you!

**Comment by charleso** [comment]
Thanks again Stephen.
