### ISSUE TITLE
Parametricity: make your application more robust & Monoid: Understanding the concept

### ISSUE THREAD

**Issue by don41382** [scalasyd/scalasyd#61]
Hey, I am working with Scala for now 7 months and would like to share some of my experiences. Since I am still a beginner, the material is not too advanced and quite good for Scala starter.

**Parametricity**
- what's the idea behind it?
- why is it important?
- a short sneak preview into Theorems for free

**Meet the Monoid**
- smooth transition from Parametricity into Monoid :)
- the idea about a Monoid
- live coding with _boxes of cookies_

**How to handle your errors**
- coming from the Java world - what changes in Scala
- harden your input possibilities
- sealed traits & disjunction
- reduce the error possibilities and ease the test pain

Presentation already exists and are ready to present. If you would like, I could present in December on the next ScalaSyd.

**Comment by charleso** [comment]
Thanks @don41382, sounds good.

I think we're actually looking pretty good for December at this stage, but keen too see this talk first next year. We often don't have a meetup in January due to people's Xmas schedules, but will try to let you know before the end of the year what the plan it.

**Comment by don41382** [comment]
@charleso sounds good to me. Just let me know once you now the dates!

**Comment by charleso** [comment]
@don41382 sorry for the delay, I can't believe it's February already! Martin's surprise visit has obviously pushed us out by a month. We're already full for March, but would you be available for speaking on the 12th April?

**Comment by don41382** [comment]
no worries. works for me

**Comment by charleso** [comment]
@don41382 Excellent! Just out of curiosity, just roughly how long is the talk?

**Comment by don41382** [comment]
30 - 40 minutes

**Comment by arnolddevos** [comment]
@don41382 Hi Felix, I trust you are still good for April?

**Comment by japgolly** [comment]
Yeah he's all good for April. (He's next to me)

**Comment by charleso** [comment]
Thanks @don41382 !
