### ISSUE TITLE
Recursion non-recursively!

### ISSUE THREAD

**Issue by japgolly** [scalasyd/scalasyd#62]
There are some absolutely fantastic discoveries that make it trivial to work with recursive data types. Unfortunately, they aren't common knowledge amongst programmers in general. A significant part of the reason is that the theory is dense with jargon, and in a form that imposes a high barrier of entry. This is a property of the medium and not the content, and so I will present algebras, coalgebras, fixpoints and various morphisms with the goal of making it comprehensible to any programmer sufficient in Scala, and without theoretic prerequisites.

I'm good to do this in December btw.

**Comment by japgolly** [comment]
Also: this needs around an hour.

**Comment by charleso** [comment]
Thanks @japgolly ! You ok to give this talk on Dec 14th?

**Comment by japgolly** [comment]
Yes, that's works for me.

**Comment by charleso** [comment]
Scheduled!

https://www.meetup.com/scalasyd/events/236084883

**Comment by charleso** [comment]
This time for sure! :) https://www.meetup.com/scalasyd/events/238094321/

**Comment by charleso** [comment]
Brilliant! Thanks @japgolly

**Comment by japgolly** [comment]
No worries @charleso, and thanks for pushing me initially; perfection and self-consciousness be damned, I'm glad I did it.

Slides and code here: https://github.com/japgolly/learning/tree/public/talks/20170308-ScalaSyd-Rercursion
I added the link to in the meetup page comments already too.
