### ISSUE TITLE
Types and a basic usecase for them

### ISSUE THREAD

**Issue by renpillay** [scalasyd/scalasyd#63]
A beginner focused talk on building a library interface to a basic RESTful API. Will involve
- A naive implementation of the library with poor practices (nulls, exposing little information through the types)
- A slightly better implementation using Options to explain how safety can be achieved
- A better implementation still using types to represent the state of the API to show how the library can help achieve both safety and be easier to use

Will likely be a short (15 minute) talk, and can be ready for January.

**Comment by charleso** [comment]
@renpillay Thanks for the proposal. We're going to skip January. How would feel about giving this in February or March? I suspect it might be the latter at this stage, but I would have to get back to you.

**Comment by renpillay** [comment]
I'm happy to do either month.

**Comment by charleso** [comment]
@renpillay We're finally back to our regular schedule. Would you be able to talk next month, on March 8th?

**Comment by renpillay** [comment]
Sounds good, I'll get some slides ready.

**Comment by charleso** [comment]
Thanks @renpillay :)

**Comment by charleso** [comment]
It's on! https://www.meetup.com/scalasyd/events/238094321/

**Comment by charleso** [comment]
@renpillay Great talk!
