### ISSUE TITLE
akka streams

### ISSUE THREAD

**Issue by stephennancekivell** [scalasyd/scalasyd#64]
* What is akka streams and reactive streams
* Comparison of a good scenario where akka streams will help.
* Connectors

This might be a longer talk ~1 hour. So Im happy to do this when ever.

**Comment by charleso** [comment]
@stephennancekivell Sorry for the delay. We've got full nights for March and April. LambdaJam is the day before the May night, so I might try to keep that clear for guest speakers who are in town. I know it's a while away but how does 14th of June sound at this stage?

**Comment by stephennancekivell** [comment]
Hi @charleso, Its good that we have so many speakers. June sounds ok at this stage, lets pencil it in.

**Comment by charleso** [comment]
Hey Stephen, still ok with June?

**Comment by stephennancekivell** [comment]
Yea mate. June will be fine.

**Comment by charleso** [comment]
Hey @stephennancekivell, did you have a friendly title/description for your talk?

**Comment by stephennancekivell** [comment]
Sure @charleso, how about.

# Akka Streams

Akka streams is a library for efficient stream data processing where the data maybe too big to fit in memory. This talk will be a intro to akka streams and stream processing architectures, as well as where it fits in the software ecosystem.

This talk will be a intro to stream processing architectures and where they fit the the ecosystem as well as a intro to the Akka streams library.

**Comment by charleso** [comment]
Thanks @stephennancekivell :)

**Comment by charleso** [comment]
Thanks (again) @stephennancekivell!
