### ISSUE TITLE
The Rise and hopefully Fall of the Aux Pattern

### ISSUE THREAD

**Issue by karlroberts** [scalasyd/scalasyd#65]
Intermediate level talk exploring some  dependant types use cases and some of the hoops we need to jump through to get them to work.

The motivation for this talk was to help make it easier to understand the code we see in libraries like Shapeless.

Should be ready Feb 2017 or at a push Jan 2017

**Comment by charleso** [comment]
@karlroberts Awesome! No rush, we don't have a meetup in Jan, Feb is already full. You available for March?

**Comment by karlroberts** [comment]
Yep book me in :-)

**Comment by charleso** [comment]
@karlroberts Sorry for the delay Karl. Martin's talk has obviously pushed us out by a month, and we're full for March already. Would you be available to speak on 12th April?

**Comment by karlroberts** [comment]
yes no problem :+1:

**Comment by charleso** [comment]
Thanks Karl!

**Comment by arnolddevos** [comment]
@karlroberts Hi Karl, I trust you are still good for April?

**Comment by charleso** [comment]
Thanks @karlroberts !
