### ISSUE TITLE
Implicits: heaven or hell? 

### ISSUE THREAD

**Issue by arnolddevos** [scalasyd/scalasyd#67]
Implicits are in the news.  We heard some of Martin's plans for this feature of the language at scalasyd in March.

# Controversy

If you ask any developer on the street they will tell you scala's implicits are a miss-feature.   If pressed they will concede that maybe using them for typeclasses is OK.   (Here a type determines the unique instance in all scopes where it is available.) 

But just passing a plain implicit parameter?  (Here the implicit scope determines which of potentially many  instances is used.) Bad idea, says the conventional wisdom.   

Martin disagrees:   "This style for me is the essence of Scala. I see lots of examples where it is used to great effects in the code we write: implicit Contexts in dotty, implicit Positions in Sebastien's tree transformers, implicits for capabilities and effects. All of it in clean first-order style, no bulky monads required. I'll bet you it's the future :slight_smile: " [1]

He sees implicit parameters as the answer for "simple effects" that don't require a continuation to model and he criticizes monads in these cases. [2]   

# Talk or Panel

I would like to talk about some of the uses of implicits, including dotty implicit functions, and generally argue the Odersky side.  

Perhaps someone can join me and argue the other side: demonstrate Reader or just put the case that use of implicits does not scale to large teams and large codebases. That it is frivolous to hide a parameter just to save some typing.

I don't expect to win the argument but I think this is might be a good way of presenting a significant aspect of the scala language.

[1] https://contributors.scala-lang.org/t/implicit-function-types/219/23
[2] https://contributors.scala-lang.org/t/implicit-function-types/219/27

**Comment by charleso** [comment]
@arnolddevos Nice idea. Might be slightly trickier to do as a panel, but I'm happy to provide some ammunition for the counter-arguments if you're just going to a talk on your own. :)

**Comment by arnolddevos** [comment]
Odersky at scaladays on more or less the same subject https://www.youtube.com/watch?v=Oij5V7LQJsA&index=1&list=PLLMLOC3WM2r5Ei2mnSHCD-ZD04AXovttL

**Comment by arnolddevos** [comment]
While I think it is a key issue given the direction of scala/dotty I have not used implicits in my code very much, except for typeclasses.  So a talk from me alone would be mostly smoke.  And this has been here for a year so I will age it out.
