### ISSUE TITLE
A problem with pattern matching in monadic code

### ISSUE THREAD

**Issue by mjhopkins** [scalasyd/scalasyd#68]
This 

```scala
  def find(glob: String): Error \/ File

  def firstLastLine(file: File): Error \/ (String, String)

  val summary = for {
    file          <- find("*.txt")
    (first, last) <- firstLastLine(file)
  } yield file + ": " + first.take(20) + "..." + last.takeRight(20)
```

fails to compile, with the error `could not find implicit value for parameter M: scalaz.Monoid[Error]`, but it's not immediately clear why, or why it *does* work when we replace `\/` with `Option`.

I'll discuss why this occurs, a simple fix to make it work, and compare with similar situations in other languages with pattern-matching and monads (Haskell, Idris, Purescript), ending by identifying a Scala feature that perhaps could be improved in future compiler versions.

This talk should be accessible to beginners.

**Comment by charleso** [comment]
@mjhopkins . Sounds interesting. How long are you expecting the talk to go for? Is there any month that would be best for you? At this stage it's likely we won't need another talk until June, or maybe even July.

**Comment by mjhopkins** [comment]
20-30 mins?

Happy to go any time.

**Comment by charleso** [comment]
@mjhopkins let's put you down for a tentative June if that's ok?

**Comment by mjhopkins** [comment]
Sure.

**Comment by charleso** [comment]
@mjhopkins still ok with June?

**Comment by charleso** [comment]
@mjhopkins Maybe make that July?

**Comment by mjhopkins** [comment]
Sure

**Comment by charleso** [comment]
You're up :)

**Comment by charleso** [comment]
@mjhopkins You have a preference for next week for this or https://github.com/scalasyd/scalasyd/issues/72?

**Comment by charleso** [comment]
Thanks @mjhopkins !
