### ISSUE TITLE
Tony Sloane: Scala and LLVM

### ISSUE THREAD

**Issue by inkytonik** [scalasyd/scalasyd#7]
We're doing some LLVM-related work in a few Scala-based projects at Macquarie, so I could talk about how we're doing that. Examples would likely be based around showing how a simple compiler can be built with our LLVM library and other tools/libraries from our group (Kiama and sbt-rats).

My preference would be not to do this one in May since the LLVM work is a bit too fresh, but June or July would be feasible. No later though, since I will be out of the country for six months from late July.

**Comment by jedws** [comment]
@inkytonik can you provide a final title and a one sentence description please? want to announce soon.

**Comment by inkytonik** [comment]
Title: Using LLVM from Scala
Description: This talk will show how LLVM intermediate representations can be created and processed by Scala code using a simple imperative language compiler as a case study.
