### ISSUE TITLE
Value, type, kind and type class, why they matter

### ISSUE THREAD

**Issue by jinilover** [scalasyd/scalasyd#70]
Introductory talk to audience new to FP.
* Explain what is a value, type, a kind and the relationship between them.
* Explain what is a type class and why it is important
* Gives examples, such as Monoid is a type class for a type, Functor is a type class for a type constructor and so on.
* Explain how Scala, a non-pure FP language, implement these FP concepts.
* Hope to make beginners easily understand the meaning of context bound and cope with the unfamiliar syntax such as F[A[_]].

**Comment by jinilover** [comment]
Hi @arnolddevos @charleso , 

As promised, I can give the talk in June.  Here is the title and description rephrased from the point form to make it a bit audience friendly.

```
Value, type, kind and type class, why they matter?

This is an introductory talk to beginners in functional programming.  
Value, type, kind and type class are fundamental concepts in FP.  The idea is straight 
forward.  But it might not be easy for beginners to understand what they are by 
learning the Scala implementation.  This talk will first introduce a value, a type, 
a kind and their relationship.  Then it will explain what is a type class, why it is 
important with some daily examples.  It will illustrate how to use Scala features to 
implement them.  Hopefully it enable the beginners to easily understand the Scala 
implementation and the unfamiliar syntax of 
func1[A: TC1 : TC2: TC3 ..., M[_]: TC11: TC12: TC3 ...]
```

**Comment by charleso** [comment]
Thanks @jinilover , looking forward to it.

**Comment by charleso** [comment]
Thanks @jinilover!
