### ISSUE TITLE
A little type theory for a lot of practical benefit

### ISSUE THREAD

**Issue by japgolly** [scalasyd/scalasyd#71]
I'd like to present a few concepts from type theory that can provide a real practical benefit to everyday coding. Along the way as part of the crescendo to main point(s), I'll also explain to beginners a few of the basics of Scala types system and syntax.

Estimated length 30-40 min.
Target audience: beginners ~ advanced *(I know I'm always optimistic about that)*

**Comment by charleso** [comment]
@japgolly Awesome. How does July sound?

**Comment by japgolly** [comment]
Actually no-go for July - sorry.
I may be able to give a talk in August --let me get back to you-- but I think I'll finally give that scalajs-react one first.

**Comment by charleso** [comment]
@japgolly No worries. August is good too. Would love to hear about scalajs-react! Let me know either way. :)

**Comment by japgolly** [comment]
np will do. May take a few weeks if that's ok.

**Comment by charleso** [comment]
@japgolly I guess there's a fairly low chance you'll be doing this talk now? It's been great having you in Sydney, we're going to miss you. :(

**Comment by japgolly** [comment]
Ah, indeed. Thanks for having me!! It's been good experiences :)
