### ISSUE TITLE
Conditional contexts

### ISSUE THREAD

**Issue by mjhopkins** [scalasyd/scalasyd#72]
Wouldn't it be nice if Scala would let you write a parametric function that would do different things, depending on whether or not a type class instance was available for the type?

For instance

* a `Set[A](a: A*)` function that creates either a `TreeSet` or a `HashSet`, depending on whether an `Ordering[A]` is in scope.
* a numerical algorithm `doCalc[N : Numeric](n: Matrix[N])` that works for all numeric types `N`, but uses a (more expensive) numerical stability technique for floating point operations, but not integral (which don't need it).

I'll run through the use and implementation of a Haskell library which provides this functionality, then show the (surprisingly simple) Scala implemention.

The talk should be accessible to beginners but hopefully also of interest to a more advanced audience. 

~30 mins but could also be compressed into a 10 min lightning talk if desired.

**Comment by charleso** [comment]
@mjhopkins Sorry for the late notice but would you be interested in doing this next month on Sep 11th?

**Comment by jedws** [comment]
@mjhopkins are you still interested in giving this talk? We need something for Wed 8 Nov
