### ISSUE TITLE
Out of Band Resource Management and Error Handling in Concurrent Programs

### ISSUE THREAD

**Issue by arnolddevos** [scalasyd/scalasyd#73]
This describes a technique I have applied on a number of projects but does not seem to be commonly used.   The idea is simple: don't pass  errors down stream, instead send them to a supervisor.  Put another way: don't include errors in the _effect_, return them from _run_.

The rationale is that downstream probably does not know how to handle the error.  And resource management is complicated (witness the long history of resource management problems in streaming libraries).

The Out of Band approach requires a few design principles be adopted.  Synchronization points must be explicit and treated as boundaries between islands of purely functional code.   The IO-like monad (IO, Task, etc) needs _Fail_ and _Recover_ states.

**Comment by etorreborre** [comment]
This is interesting. My experience with resource management in [eff](https://github.com/atnos-org/eff) is also that resource management really has to be "baked-in" the "effect" monad.

**Comment by arnolddevos** [comment]
The approach I am alluding to predates eff AFAIK.  It is certainly not as sophisticated.   

The Task-like monad here is called Process[T] (apologies to fs2).   It has baked-in Failed and Recoverable cases.  

If p1 is a Process[T] then p2 = (p1 recoverWith r) is a Process[T] that will cause a side effect if it reaches the Failed state when run.  The _r_ is (a function yielding) a Process that captures the recovery side effect. It could embody a  resource and the steps to dispose it.  

You are probably thinking of something like a file descriptor as the _resource_.  But it could be a message that must not be lost.  Let's say p2 is part of p0 which is a Process[Nothing] that runs forever absent failures. The recovery might send the message to the dead letter queue and restart p0.

**Comment by etorreborre** [comment]
One thing which I found useful was to protect a resource, regardless of the successive binds done with it:
```
val action1: Process[Int] = bracket(getResource)(useResource)(closeResource)

val action2: Process[Int] = action1 flatMap { i =>
   pure(i + 1)
}
```
If you run `action2` the resource should be closed when `action2` has finished executing (even if there is an exception in there). Can `Process` do that?

**Comment by arnolddevos** [comment]
I did not have an exact equivalent so I wrote this (type checked but untested):

```scala
  def bracket[R, T](acquire: Process[R])(use: R => Process[T])(dispose: R => Process[Unit]): Process[T] =
    acquire >>= (r => (use(r) recoverWith dispose(r)) >>= (t => dispose(r) >> stop(t)))
```

where recoverWith is as discussed above and stop is pure (sorry for the funny name!)

Looks like a monadic try-catch no?

**Comment by etorreborre** [comment]
My question is: what happens if you `flatMap` other actions on top of a "bracketed" action? I found it useful to be able to do that and still have the `dispose` action done at the end:
```scala
def readLines(path: String): Process[List[String]] = 
  bracket(getFile(path))(file => file.getLines)(file => close(file))

val numbers: Process[List[Int]] = 
  readLines("path").map(line => line.toInt)
```

**Comment by arnolddevos** [comment]
I would write numbers like this:-

```scala
val numbers: Process[List[Int]] = 
  readLines("path").map(lines => lines.map(_.toInt))
```
And yes, the file is closed no matter what.  Specifically:- 

1. If `getLines` is Failed (underlying IOException), `readLines` and `numbers` are thence `Failed` which is a `Process[Nothing]` and the file is closed by the out-of-band recovery.

2. If `getLines` completes, then the file is closed before the conversion to Int occurs.  Because we wrote bracket with `>>` aka flatMap connecting dispose and stop (pure).

3. [Edit 1] If the `toInt` throws, then `number` is Failed but the file was closed before `readLines` completed and `toInt` was called.

Note that `Process` is not a stream it is like `Task`.  `Cofree[Process, T]` would be an (unbounded) stream.

[Edit 2]  I have to assume `file.getLines` is a `Process[List[String]]`.  See the signature I assumed for `bracket`.

**Comment by charleso** [comment]
@arnolddevos How did you feel about giving this (or another talk) in July?

**Comment by arnolddevos** [comment]
@charleso Hi, yes I am up to give a talk.  However I am reconsidering what subject would be interesting and for which part of the audience.

**Comment by charleso** [comment]
@arnolddevos Sounds like scala.js would be Sep, did you want to keep aiming for Aug then?

**Comment by arnolddevos** [comment]
@charleso OK.

**Comment by charleso** [comment]
@arnolddevos You mind updating the title/description (or posting a new comment) for the meetup next week? Cheers.

**Comment by jedws** [comment]
@arnolddevos should talk/issue this be closed now? you gave a talk, but not really this one, in Aug 2017

**Comment by arnolddevos** [comment]
@jedws yes I will close this one.   there are a couple of other talk ideas around implicits I proposed that never got traction so I will close those too if that is OK.
