### ISSUE TITLE
Beginner talk on Optics

### ISSUE THREAD

**Issue by renpillay** [scalasyd/scalasyd#75]
I think there have been a few Optics talks, but given that we generally have a good percentage of first timers, I could do another one.

Probably beginner focused, talking about why we would use optics, definitions of Iso/Lens/Prism/Optional, and some basic examples of where they'd be used in the real world.

**Comment by charleso** [comment]
@renpillay Sounds great! We haven't had a lens talk for a while. How did you feel about talking on the 9th of August?

**Comment by renpillay** [comment]
Sooner than I planned, but sure - I can get something ready for that date.

**Comment by charleso** [comment]
Yeah sorry, we already have pretty concrete plans for September around Scala.js but need one more talk for August. No pressure, but if you have enough time to prepare that would be awesome!

**Comment by renpillay** [comment]
I was actually thinking October, since I'll be away in September. But August works :)

**Comment by charleso** [comment]
@renpillay You got a title/description for the meetup next week?

**Comment by renpillay** [comment]
@charleso 

Title: Introduction to Optics
Description: This talk will walk through some issues with manipulating data in immutable data structures and how Optics can simplify these problems.

**Comment by charleso** [comment]
@renpillay Thanks! See you next Wednesday. :)

**Comment by charleso** [comment]
Thanks @renpillay!
