### ISSUE TITLE
Taming Transducer Data from the Electric Power Network

### ISSUE THREAD

**Issue by arnolddevos** [scalasyd/scalasyd#76]
We developed a metrics recording system for electric power operations and planning. 

This talk describes the component, written in scala, that reduces volumes of noisy, irregular transducer measurements to regular time series of reasonable dimensions and other summaries.  

It is a service, driven by a domain-specific language, fronting a Cassandra cluster.  I will describe its design and implementation, drilling down to the scala level in the most interesting areas.

**Comment by arnolddevos** [comment]
@charleso Hi Charles, I thought it best to create a new issue and put it in calendar.  Hope you agree.

**Comment by charleso** [comment]
@arnolddevos Brilliant. Thanks for that!

**Comment by charleso** [comment]
Thanks @arnolddevos
