### ISSUE TITLE
SBT plugins for no fun and little profit

### ISSUE THREAD

**Issue by triggerNZ** [scalasyd/scalasyd#78]
An overview of how SBT plugins work. 

Both for those who want to write plugins and those who just want to control their build better.

- Explaining project structure
- An example plugin
- Settings, tasks and commands
- Navigating third-party settings and code.

**Comment by charleso** [comment]
Thanks @triggerNZ, when were you available/thinking about doing the talk? Would next month be too soon? (I'm assuming Jed poked you)

**Comment by arnolddevos** [comment]
+1 I don't think we have had an sbt talk.  "no fun" undersells it a little ;-)

**Comment by charleso** [comment]
@triggerNZ You free for next month on Sep 11th?

**Comment by triggerNZ** [comment]
@charleso assuming you mean Oct 11th, yes. Sorry I didn't reply to your earlier comment, the notification got lost somehow...

**Comment by charleso** [comment]
@triggerNZ Whoops. Yep that's what I meant. Phew - thanks for that!

**Comment by charleso** [comment]
Sorry for the late announcement. https://www.meetup.com/scalasyd/events/243959862/
