### ISSUE TITLE
Combining Free and FreeAp in the wild

### ISSUE THREAD

**Issue by camjo** [scalasyd/scalasyd#79]
Talk about using the Free Monad in the wild and how to introduce parallelism into your Free programs with FreeAp.

Has a focus on practicality rather than type theory.

**Comment by charleso** [comment]
Sounds great @camjo! How much time did you need to prepare? Would next month (11 Oct) be too soon?

**Comment by camjo** [comment]
Should be enough time. I've given a version of this talk at my company already. I'll just have to polish up the slides a bit!

**Comment by charleso** [comment]
@camjo Excellent and thanks! You're locked in!

**Comment by charleso** [comment]
Sorry for the late announcement. https://www.meetup.com/scalasyd/events/243959862/
