### ISSUE TITLE
Eff Monad

### ISSUE THREAD

**Issue by caobinzi** [scalasyd/scalasyd#81]
I would like to share some experiences about the Eff Monad library created by Eric Torreborre 
@etorreborre https://github.com/atnos-org/eff

1. Some basic FP concepts 
2. Why Eff Monad
3. Eff Monad by examples

**Comment by jedws** [comment]
thanks @caobinzi, when would you be able to present? Would this Wednesday be possible?

**Comment by caobinzi** [comment]
@jedws No problem.  This Wednesday looks good to me.

**Comment by jedws** [comment]
awesome. could you please provide a title and a short description we can put up on the meetup page?

**Comment by caobinzi** [comment]
@jedws , sure


---------------------------------------------------------------------------
Eff Monad

Binzi Cao

In this talk, we'll introduce Eff Monad and share some examples based on the library:

https://github.com/atnos-org/eff

The topics includes:

• Some basic FP concepts

• The road to Eff Monad and why it matters

• Eff Monad by examples
