### ISSUE TITLE
Refactor Ugly procedural code to idiomatic scala

### ISSUE THREAD

**Issue by karlroberts** [scalasyd/scalasyd#82]
I have some hacked together procedural mutable code, and successively refactor it  to clean immutable idiomatic scala.

The Idea is to take the procedural idom and show to think of it in a functional way. 
This is not a big bang refactor but a successive refactor to gently move the code into a better dry-er less bug prone state

Should be suitable from intro level or Java devs looking at Scala and also is a good reminder for more advanced Scala devs.

Cheers

Karl

PS talk not yet written but have code so should not take too long to put together a talk

**Comment by jedws** [comment]
@karlroberts ok to do this next week?

**Comment by karlroberts** [comment]
oops sorry been busy. missed that. I can try to get it ready for Wed 9th May?

**Comment by kevin-lee** [comment]
@karlroberts Sure. That's great! We will schedule it for the 9th of May. Thank you!

@jedws I still don't have permission to add or change the label.

**Comment by karlroberts** [comment]
ok thanks.

**Comment by jedws** [comment]
@Kevin-Lee sorry mate, invite sent

**Comment by kevin-lee** [comment]
@jedws Thank you!

**Comment by kevin-lee** [comment]
@karlroberts Kerl, could you please send me the title and one paragraph abstract of the talk?
