### ISSUE TITLE
Life Is A Comonad

### ISSUE THREAD

**Issue by eli-jordan** [scalasyd/scalasyd#83]
I have recently been grappling with the concept of a Comonad, and found that there are quite a few articles that explain their theoretical footing, but not many that convey an intuitive understanding of Comonads using practical examples. 

In this talk I will introduce comonads using the Zipper data structure as an analogy, then show how the Store comonad can be used to implement Conway's Game Of Life.

I have a blog post on the same topic here https://eli-jordan.github.io/2018/02/16/life-is-a-comonad/

@jedws - as requested

**Comment by jedws** [comment]
@eli-jordan do you think you'd be ready for March? Will schedule in if you are.

**Comment by eli-jordan** [comment]
@jedws Would that be 14th March? If so, yeah I should be able to put some slides together by then.
How long are the slots? (I was thinking maybe 30min)

**Comment by jedws** [comment]
yep, 14th March. There isn't a set time limit, anything from 30-50 mins is sweet, outside that less preferable but not necessarily outlawed.

**Comment by eli-jordan** [comment]
@jedws I have been notified that I have to travel for work at the last minute. So I won't have a chance to prepare for the March event. But I am happy to do the talk in April.

**Comment by jedws** [comment]
ah, no worries, understood.

**Comment by jedws** [comment]
@eli-jordan still ok to do this next week?

**Comment by eli-jordan** [comment]
@jedws Yeah, will be ready for next Wednesday

**Comment by jedws** [comment]
excellent! will schedule in the next day or so when I finalise the last two spots

**Comment by eli-jordan** [comment]
@jedws Is this locked in for next week?

**Comment by jedws** [comment]
yep

**Comment by eli-jordan** [comment]
@jedws Ok great, I haven't seen the meetup event scheduled yet. Will that be up today? (Want to share with my colleagues)

**Comment by jedws** [comment]
sorry, been distracted https://www.meetup.com/scalasyd/events/249590115/

**Comment by eli-jordan** [comment]
No worries. Thanks for the quick update!
