### ISSUE TITLE
Scala In Production

### ISSUE THREAD

**Issue by FabFlying** [scalasyd/scalasyd#84]
Review of the experience of developing and running an eCommerce website written in Scala.

**Comment by kevin-lee** [comment]
@FabFlying Thanks for the proposal. It sounds good. Could you do it in May?

**Comment by kevin-lee** [comment]
@jedws I have no permission to put any label here.

**Comment by FabFlying** [comment]
May is fine.

**Comment by kevin-lee** [comment]
@FabFlying That's great! We will schedule it for the 9th of May. Thank you!

**Comment by kevin-lee** [comment]
@jedws I still have no permission to change or add any labels.

**Comment by kevin-lee** [comment]
@jedws Could you please tell me the date and time for ScalaSyd ep 62? I don't have your personal email address so can't contact you through email.

**Comment by Kevin-Lee** [comment]
@jedws Mine is 
hello at kevinlee.io
